/*
 * Sky Culture Maker plug-in for Stellarium
 *
 * Copyright (C) 2025 Vincent Gerlach
 * Copyright (C) 2025 Luca-Philipp Grumbach
 * Copyright (C) 2025 Fabian Hofer
 * Copyright (C) 2025 Mher Mnatsakanyan
 * Copyright (C) 2025 Richard Hofmann
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef SCMBOUNDARYDIALOG_HPP
#define SCMBOUNDARYDIALOG_HPP

#include "SkyCultureMaker.hpp"
#include "StelDialogSeparate.hpp"

namespace scm
{
class ScmBoundary;
class ScmBoundaryDraw;
}

class Ui_ScmBoundaryDialogClass;

class ScmBoundaryDialog : public StelDialogSeparate
{
	Q_OBJECT

public:
	explicit ScmBoundaryDialog(SkyCultureMaker *maker);
	~ScmBoundaryDialog() override;

	scm::ScmBoundary *getBoundary() const { return boundary; }
	scm::ScmBoundaryDraw *getBoundaryDraw() const { return boundaryDraw; }

	void updatePreview();

public slots:
	void retranslate() override;
	void close() override;
	void onBrowseFile();
	void onPrecisionSpinBoxChanged();
	void updatePrecisionFromSpinBoxes();
	void onToolChanged(bool checked);
	void onUndo();
	void onClearAll();
	void onCopyPreview();
	void onRefreshPreview();
	void onSaveFile();
	void onDataChanged();

protected:
	void createDialogContent() override;

private:
	void setupConnections();
	void populateConstellationComboBox(QComboBox *combo) const;
	QString getConstellationAbbreviation(const QComboBox *combo) const;
	QString formatRA(double ra) const;
	QString formatDec(double dec) const;
	
	int countEdgeLines(const QString &text) const;
	QStringList extractEdgeLines(const QString &text) const;
	QString removeLastEdgeLines(const QString &text, int count) const;
	QString insertEdgeLines(const QString &text, const QStringList &lines) const;

	Ui_ScmBoundaryDialogClass *ui = nullptr;
	SkyCultureMaker *maker = nullptr;
	scm::ScmBoundary *boundary = nullptr;
	scm::ScmBoundaryDraw *boundaryDraw = nullptr;

	QStringList constellationAbbreviations;
	QMap<QString, QString> constellationMap;

	bool manualEditMode = false;
	QString lastAutoGeneratedPreview;
};

#endif
