/*
 * Sky Culture Maker plug-in for Stellarium
 *
 * Copyright (C) 2025 Vincent Gerlach
 * Copyright (C) 2025 Luca-Philipp Grumbach
 * Copyright (C) 2025 Fabian Hofer
 * Copyright (C) 2025 Mher Mnatsakanyan
 * Copyright (C) 2025 Richard Hofmann
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include "ScmBoundaryDialog.hpp"
#include "ui_ScmBoundaryDialogClass.h"
#include "ScmBoundary.hpp"
#include "ScmBoundaryDraw.hpp"
#include "types/DrawTools.hpp"
#include "StelApp.hpp"

#include <QFileDialog>
#include <QMessageBox>
#include <QClipboard>
#include <QApplication>
#include <QLineEdit>
#include <QComboBox>
#include <QDebug>
#include <QTimer>
#include <QSet>
#include <QVector>
#include <cmath>

ScmBoundaryDialog::ScmBoundaryDialog(SkyCultureMaker *maker)
	: StelDialogSeparate("ScmBoundaryDialog")
	, maker(maker)
{
	ui = new Ui_ScmBoundaryDialogClass;
	boundary = new scm::ScmBoundary(this);
	boundaryDraw = new scm::ScmBoundaryDraw(boundary, this);

	constellationAbbreviations = {
		"And", "Ant", "Aps", "Aql", "Aqr", "Ara", "Ari", "Aur", "Boo", "CMa",
		"CMi", "CVn", "Cae", "Cam", "Cap", "Car", "Cas", "Cen", "Cep", "Cet",
		"Cha", "Cir", "Cnc", "Col", "Com", "CrA", "CrB", "Crt", "Cru", "Crv",
		"Cyg", "Del", "Dor", "Dra", "Equ", "Eri", "For", "Gem", "Gru", "Her",
		"Hor", "Hya", "Hyi", "Ind", "LMi", "Lac", "Leo", "Lep", "Lib", "Lup",
		"Lyn", "Lyr", "Men", "Mic", "Mon", "Mus", "Nor", "Oct", "Oph", "Ori",
		"Pav", "Peg", "Per", "Phe", "Pic", "PsA", "Psc", "Pup", "Pyx", "Ret",
		"Scl", "Sco", "Sct", "Ser", "Sex", "Sge", "Sgr", "Tau", "Tel", "TrA",
		"Tri", "Tuc", "UMa", "UMi", "Vel", "Vir", "Vol", "Vul"
	};
}

ScmBoundaryDialog::~ScmBoundaryDialog()
{
	if (ui)
	{
		delete ui;
		ui = nullptr;
	}
}

void ScmBoundaryDialog::createDialogContent()
{
	ui->setupUi(dialog);

	populateConstellationComboBox(ui->defaultConstellation1ComboBox);
	populateConstellationComboBox(ui->defaultConstellation2ComboBox);

	setupConnections();

	connect(ui->previewTextEdit, &QTextEdit::textChanged, this, [this]() {
		QString current = ui->previewTextEdit->toPlainText();
		if (current != lastAutoGeneratedPreview && !lastAutoGeneratedPreview.isEmpty())
		{
			manualEditMode = true;
		}
	});

	// 设置默认精度为1度
	updatePrecisionFromSpinBoxes();

	connect(&StelApp::getInstance(), SIGNAL(languageChanged()), this, SLOT(retranslate()));
}

void ScmBoundaryDialog::retranslate()
{
	if (dialog)
	{
		ui->retranslateUi(dialog);
	}
}

void ScmBoundaryDialog::close()
{
	if (dialog)
	{
		dialog->close();
	}
}

void ScmBoundaryDialog::setupConnections()
{
	// 标题栏
	connect(ui->titleBar, &TitleBar::closeClicked, this, &ScmBoundaryDialog::close);
	connect(ui->titleBar, &TitleBar::movedTo, this, &ScmBoundaryDialog::handleMovedTo);

	// 文件浏览
	connect(ui->browseFileButton, &QPushButton::clicked, this, &ScmBoundaryDialog::onBrowseFile);

	// 赤经精度输入框 (h/m/s)
	connect(ui->raHourSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), this, &ScmBoundaryDialog::onPrecisionSpinBoxChanged);
	connect(ui->raMinuteSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), this, &ScmBoundaryDialog::onPrecisionSpinBoxChanged);
	connect(ui->raSecondSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), this, &ScmBoundaryDialog::onPrecisionSpinBoxChanged);

	// 赤纬精度输入框 (°/'/")
	connect(ui->degreeSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), this, &ScmBoundaryDialog::onPrecisionSpinBoxChanged);
	connect(ui->minuteSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), this, &ScmBoundaryDialog::onPrecisionSpinBoxChanged);
	connect(ui->secondSpinBox, QOverload<int>::of(&QSpinBox::valueChanged), this, &ScmBoundaryDialog::onPrecisionSpinBoxChanged);

	// 默认星座下拉框
	connect(ui->defaultConstellation1ComboBox, &QComboBox::currentTextChanged, this, [this](const QString &) {
		boundary->setDefaultConstellations(
			getConstellationAbbreviation(ui->defaultConstellation1ComboBox),
			getConstellationAbbreviation(ui->defaultConstellation2ComboBox)
		);
	});
	connect(ui->defaultConstellation2ComboBox, &QComboBox::currentTextChanged, this, [this](const QString &) {
		boundary->setDefaultConstellations(
			getConstellationAbbreviation(ui->defaultConstellation1ComboBox),
			getConstellationAbbreviation(ui->defaultConstellation2ComboBox)
		);
	});

	// 工具按钮
	connect(ui->penToolButton, &QPushButton::toggled, this, &ScmBoundaryDialog::onToolChanged);
	connect(ui->eraserToolButton, &QPushButton::toggled, this, &ScmBoundaryDialog::onToolChanged);
	connect(ui->undoButton, &QPushButton::clicked, this, &ScmBoundaryDialog::onUndo);
	connect(ui->clearAllButton, &QPushButton::clicked, this, &ScmBoundaryDialog::onClearAll);

	// 预览
	connect(ui->copyPreviewButton, &QPushButton::clicked, this, &ScmBoundaryDialog::onCopyPreview);
	connect(ui->refreshPreviewButton, &QPushButton::clicked, this, &ScmBoundaryDialog::onRefreshPreview);

	// 底部按钮
	connect(ui->saveButton, &QPushButton::clicked, this, &ScmBoundaryDialog::onSaveFile);
	connect(ui->closeButton, &QPushButton::clicked, this, &ScmBoundaryDialog::close);

	// 数据变化
	connect(boundary, &scm::ScmBoundary::dataChanged, this, &ScmBoundaryDialog::onDataChanged);
	connect(boundaryDraw, &scm::ScmBoundaryDraw::boundaryChanged, this, &ScmBoundaryDialog::onDataChanged);
	connect(boundaryDraw, &scm::ScmBoundaryDraw::pointAdded, this, [this](double, double) {
		updatePreview();
	});
}

void ScmBoundaryDialog::onBrowseFile()
{
	QString filePath = QFileDialog::getOpenFileName(dialog,
		q_("选择星空文化文件"),
		QString(),
		q_("JSON Files (*.json)"));

	if (!filePath.isEmpty())
	{
		ui->filePathLineEdit->setText(filePath);
		boundary->loadConstellationsFromJson(filePath);

		constellationMap = boundary->getConstellationMap();
		constellationAbbreviations = boundary->getConstellationAbbreviations();

		QString c1 = getConstellationAbbreviation(ui->defaultConstellation1ComboBox);
		QString c2 = getConstellationAbbreviation(ui->defaultConstellation2ComboBox);
		ui->defaultConstellation1ComboBox->clear();
		ui->defaultConstellation2ComboBox->clear();
		populateConstellationComboBox(ui->defaultConstellation1ComboBox);
		populateConstellationComboBox(ui->defaultConstellation2ComboBox);

		// 尝试恢复之前选择的星座（在显示文本中查找匹配缩写的项）
		for (int i = 0; i < ui->defaultConstellation1ComboBox->count(); ++i)
		{
			QString text = ui->defaultConstellation1ComboBox->itemText(i);
			if (text.startsWith(c1 + " ") || text == c1)
			{
				ui->defaultConstellation1ComboBox->setCurrentIndex(i);
				break;
			}
		}
		for (int i = 0; i < ui->defaultConstellation2ComboBox->count(); ++i)
		{
			QString text = ui->defaultConstellation2ComboBox->itemText(i);
			if (text.startsWith(c2 + " ") || text == c2)
			{
				ui->defaultConstellation2ComboBox->setCurrentIndex(i);
				break;
			}
		}

		boundary->setDefaultConstellations(
			getConstellationAbbreviation(ui->defaultConstellation1ComboBox),
			getConstellationAbbreviation(ui->defaultConstellation2ComboBox)
		);

		ui->epochLabel->setText(q_("历元: %1").arg(boundary->getEdgesEpoch()));

		updatePreview();
	}
}

void ScmBoundaryDialog::onPrecisionSpinBoxChanged()
{
	updatePrecisionFromSpinBoxes();
}

void ScmBoundaryDialog::updatePrecisionFromSpinBoxes()
{
	// 赤经精度 (时间单位: h/m/s)
	int raHours = ui->raHourSpinBox->value();
	int raMinutes = ui->raMinuteSpinBox->value();
	int raSeconds = ui->raSecondSpinBox->value();

	double raStepSeconds = raHours * 3600.0 + raMinutes * 60.0 + raSeconds;

	if (raStepSeconds <= 0)
	{
		raStepSeconds = 600.0; // 默认10分钟
		ui->raHourSpinBox->setValue(0);
		ui->raMinuteSpinBox->setValue(10);
		ui->raSecondSpinBox->setValue(0);
	}

	int raDenominator = static_cast<int>(86400.0 / raStepSeconds);
	if (raDenominator <= 0) raDenominator = 144;

	qDebug() << "RA precision: hours=" << raHours << "min=" << raMinutes << "sec=" << raSeconds
			<< "stepSeconds=" << raStepSeconds << "denominator=" << raDenominator;

	boundary->setPrecisionDenominatorRA(raDenominator);

	// 赤纬精度 (角度单位: °/'/")
	int degrees = ui->degreeSpinBox->value();
	int minutes = ui->minuteSpinBox->value();
	int seconds = ui->secondSpinBox->value();

	double decStepDegrees = degrees + minutes / 60.0 + seconds / 3600.0;

	if (decStepDegrees <= 0)
	{
		decStepDegrees = 1.0;
		ui->degreeSpinBox->setValue(1);
		ui->minuteSpinBox->setValue(0);
		ui->secondSpinBox->setValue(0);
	}

	int decDenominator = static_cast<int>(360.0 / decStepDegrees);
	if (decDenominator <= 0) decDenominator = 360;

	qDebug() << "Dec precision: degrees=" << degrees << "min=" << minutes << "sec=" << seconds
			<< "stepDegrees=" << decStepDegrees << "denominator=" << decDenominator;

	boundary->setPrecisionDenominatorDec(decDenominator);

	QList<scm::ScmBoundaryEdge> edges = boundary->getEdges();
	for (int i = 0; i < edges.size(); ++i)
	{
		boundary->updateEdgeData(i);
	}

	manualEditMode = false;
	lastAutoGeneratedPreview.clear();
	updatePreview();
}

void ScmBoundaryDialog::onToolChanged(bool checked)
{
	Q_UNUSED(checked);

	if (ui->penToolButton->isChecked())
	{
		boundaryDraw->setTool(scm::DrawTools::Pen);
		ui->eraserToolButton->setChecked(false);
	}
	else if (ui->eraserToolButton->isChecked())
	{
		boundaryDraw->setTool(scm::DrawTools::Eraser);
		ui->penToolButton->setChecked(false);
	}
	else
	{
		boundaryDraw->setTool(scm::DrawTools::None);
	}
}

void ScmBoundaryDialog::onUndo()
{
	boundaryDraw->undoLastPoint();
}

void ScmBoundaryDialog::onClearAll()
{
	manualEditMode = false;
	lastAutoGeneratedPreview.clear();
	boundaryDraw->resetDrawing();
}

int ScmBoundaryDialog::countEdgeLines(const QString &text) const
{
	QStringList lines = text.split('\n');
	int edgesStart = -1;
	int count = 0;
	for (int i = 0; i < lines.size(); ++i)
	{
		if (lines[i].contains("\"edges\":"))
		{
			edgesStart = i;
			continue;
		}
		if (edgesStart >= 0)
		{
			QString trimmed = lines[i].trimmed();
			if (trimmed == "]" || trimmed == "],") break;
			if (!trimmed.isEmpty()) count++;
		}
	}
	return count;
}

QStringList ScmBoundaryDialog::extractEdgeLines(const QString &text) const
{
	QStringList lines = text.split('\n');
	QStringList edgeLines;
	int edgesStart = -1;
	for (int i = 0; i < lines.size(); ++i)
	{
		if (lines[i].contains("\"edges\":"))
		{
			edgesStart = i;
			continue;
		}
		if (edgesStart >= 0)
		{
			QString trimmed = lines[i].trimmed();
			if (trimmed == "]" || trimmed == "],") break;
			if (!trimmed.isEmpty()) edgeLines.append(lines[i]);
		}
	}
	return edgeLines;
}

QString ScmBoundaryDialog::removeLastEdgeLines(const QString &text, int count) const
{
	if (count <= 0) return text;

	QStringList lines = text.split('\n');
	int edgesStart = -1;
	int edgesEnd = -1;
	for (int i = 0; i < lines.size(); ++i)
	{
		if (lines[i].contains("\"edges\":"))
		{
			edgesStart = i;
		}
		if (edgesStart >= 0 && i > edgesStart)
		{
			QString trimmed = lines[i].trimmed();
			if (trimmed == "]" || trimmed == "],")
			{
				edgesEnd = i;
				break;
			}
		}
	}

	if (edgesStart < 0 || edgesEnd < 0) return text;

	QVector<int> edgeLineIndices;
	for (int i = edgesStart + 1; i < edgesEnd; ++i)
	{
		QString trimmed = lines[i].trimmed();
		if (!trimmed.isEmpty())
		{
			edgeLineIndices.append(i);
		}
	}

	int toRemove = qMin(count, edgeLineIndices.size());
	if (toRemove <= 0) return text;

	QSet<int> linesToRemove;
	for (int i = edgeLineIndices.size() - toRemove; i < edgeLineIndices.size(); ++i)
	{
		linesToRemove.insert(edgeLineIndices[i]);
	}

	QStringList newLines;
	for (int i = 0; i < lines.size(); ++i)
	{
		if (!linesToRemove.contains(i))
		{
			newLines.append(lines[i]);
		}
	}

	return newLines.join("\n");
}

QString ScmBoundaryDialog::insertEdgeLines(const QString &text, const QStringList &lines) const
{
	if (lines.isEmpty()) return text;

	int idx = text.lastIndexOf("  ]");
	if (idx < 0) idx = text.lastIndexOf("]");

	if (idx < 0) return text;

	QString toInsert = lines.join("\n") + "\n";
	QString result = text;
	result.insert(idx, toInsert);
	return result;
}

void ScmBoundaryDialog::updatePreview()
{
	QString generated = boundary->toExportString();
	QString oldGenerated = lastAutoGeneratedPreview;
	lastAutoGeneratedPreview = generated;

	if (!manualEditMode)
	{
		{
			QSignalBlocker blocker(ui->previewTextEdit);
			ui->previewTextEdit->setPlainText(generated);
		}
		return;
	}

	if (oldGenerated.isEmpty())
	{
		QString currentText = ui->previewTextEdit->toPlainText();
		if (currentText.trimmed().isEmpty())
		{
			QSignalBlocker blocker(ui->previewTextEdit);
			ui->previewTextEdit->setPlainText(generated);
		}
		else
		{
			QStringList newEdgeLines = extractEdgeLines(generated);
			QString updatedText = insertEdgeLines(currentText, newEdgeLines);
			QSignalBlocker blocker(ui->previewTextEdit);
			ui->previewTextEdit->setPlainText(updatedText);
		}
		return;
	}

	int oldEdgeCount = countEdgeLines(oldGenerated);
	int newEdgeCount = countEdgeLines(generated);
	QString currentText = ui->previewTextEdit->toPlainText();

	if (newEdgeCount > oldEdgeCount)
	{
		QStringList newEdgeLines = extractEdgeLines(generated);

		QStringList addedLines;
		for (int i = oldEdgeCount; i < newEdgeCount && i < newEdgeLines.size(); ++i)
		{
			addedLines.append(newEdgeLines[i]);
		}

		QString updatedText = insertEdgeLines(currentText, addedLines);
		{
			QSignalBlocker blocker(ui->previewTextEdit);
			ui->previewTextEdit->setPlainText(updatedText);
		}
	}
	else if (newEdgeCount < oldEdgeCount)
	{
		int removedCount = oldEdgeCount - newEdgeCount;
		QString updatedText = removeLastEdgeLines(currentText, removedCount);
		{
			QSignalBlocker blocker(ui->previewTextEdit);
			ui->previewTextEdit->setPlainText(updatedText);
		}
	}
}

void ScmBoundaryDialog::onDataChanged()
{
	updatePreview();
}

void ScmBoundaryDialog::onCopyPreview()
{
	QClipboard *clipboard = QApplication::clipboard();
	clipboard->setText(ui->previewTextEdit->toPlainText());
}

void ScmBoundaryDialog::onRefreshPreview()
{
	manualEditMode = false;
	lastAutoGeneratedPreview.clear();
	updatePreview();
}

void ScmBoundaryDialog::onSaveFile()
{
	QString filePath = QFileDialog::getSaveFileName(dialog,
		q_("保存边界数据"),
		QString(),
		q_("JSON Files (*.json)"));

	if (!filePath.isEmpty())
	{
		if (!filePath.endsWith(".json", Qt::CaseInsensitive))
		{
			filePath += ".json";
		}

		QFile file(filePath);
		if (file.open(QIODevice::WriteOnly | QIODevice::Text))
		{
			QTextStream out(&file);
			out << ui->previewTextEdit->toPlainText();
			file.close();
			QMessageBox::information(dialog, q_("保存成功"),
				q_("边界数据已保存到：") + filePath);
		}
		else
		{
			QMessageBox::warning(dialog, q_("保存失败"),
				q_("无法写入文件：") + filePath);
		}
	}
}

void ScmBoundaryDialog::populateConstellationComboBox(QComboBox *combo) const
{
	combo->addItem("");

	if (constellationMap.isEmpty())
	{
		for (const QString &abbr : constellationAbbreviations)
		{
			combo->addItem(abbr);
		}
	}
	else
	{
		for (const QString &abbr : constellationAbbreviations)
		{
			QString nativeName = constellationMap.value(abbr, "");
			if (nativeName.isEmpty() || nativeName == abbr)
			{
				combo->addItem(abbr);
			}
			else
			{
				combo->addItem(abbr + " " + nativeName);
			}
		}
	}
}

QString ScmBoundaryDialog::getConstellationAbbreviation(const QComboBox *combo) const
{
	QString text = combo->currentText().trimmed();
	if (text.isEmpty())
		return "";

	int spaceIdx = text.indexOf(' ');
	if (spaceIdx > 0)
	{
		return text.left(spaceIdx).trimmed();
	}

	return text;
}